### ISSUE TITLE
Possible MIT Licence for NCast project

### ISSUE THREAD

**Issue by jeremylcarter** [tmds/Tmds.MDns#1]
I would like to use your MDns project in a MIT licensed project called NCast. Kindly look over the NCast project and let me know if you can allow your MDns to be licensed for MIT licence.
https://github.com/jeremychild/NCast

**Comment by JaggerJo** [comment]
Hey @tmds 👋

really nice library - I'm interested in using it in a closed source commercial product. 

From how I interpret the LGPL 2.1 license this is only legal if we ship the your library as a separate (dynamically linked) dll. In our case we use NativeAOT - so all libraries would be baked in our binary / it would be statically linked - which would require use to do really complicated things if we'd want to use your library to comply with the LGPL license - as we'd need to allow users to swap in their own version of your library (which is quite a task).

I'm not a lawyer but I have published a few libraries ([FuncUI](https://github.com/fsprojects/Avalonia.FuncUI), [Echoes](https://github.com/Voyonic-Systems/Echoes/tree/main), ..) under the MIT license - as it's much simpler to comply with. 

Depending on what your goal is with the license I could imagine that the MIT license is simpler to comply with / comes with less baggage. In the end I respect your choice - no matter what - it's your code. Just want to make sure this is intentional before we consider different libraries.

**Comment by tmds** [comment]
hi @JaggerJo, yes, with LGPL 2.1 you can't use this with NativeAOT. I'll change the license to be MIT. I'll look into it before the end of August.

**Comment by JaggerJo** [comment]
> hi [@JaggerJo](https://github.com/JaggerJo), yes, with LGPL 2.1 you can't use this with NativeAOT. I'll change the license to be MIT. I'll look into it before the end of August.

Great news! Thanks 🙏

**Comment by tmds** [comment]
v0.9.0 is available on nuget.org under the MIT license.
